<?php

namespace Database\Seeders;

use App\Models\Pelamar;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PelamarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Pelamar::insert([
            [
                'id' => 1,
                'lowongan_id' => 1,
                'nama' => 'Afiya nanda',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'afiyananda@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 2,
                'lowongan_id' => 1,
                'nama' => 'agelia wati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ageliawati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 3,
                'lowongan_id' => 1,
                'nama' => 'agung zainuri',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'agungzainuri@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 4,
                'lowongan_id' => 1,
                'nama' => 'ahmad akhqiq',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'ahmadakhqiq@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 5,
                'lowongan_id' => 1,
                'nama' => 'alfarizi',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'alfarizi@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 6,
                'lowongan_id' => 1,
                'nama' => 'ana fatmawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'anafatmawati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 7,
                'lowongan_id' => 1,
                'nama' => 'aprilia indah nur jannah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'apriliaindahnurjannah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 8,
                'lowongan_id' => 1,
                'nama' => 'syabilatur rahma',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'syabilaturrahma@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 9,
                'lowongan_id' => 1,
                'nama' => 'cicik syahada',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ciciksyahada@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 10,
                'lowongan_id' => 1,
                'nama' => 'denny setiawan',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'dennysetiawan@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 11,
                'lowongan_id' => 1,
                'nama' => 'eka febrianti',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ekafebrianti@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 12,
                'lowongan_id' => 1,
                'nama' => 'evi kumalasari',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'evikumalasari@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 13,
                'lowongan_id' => 2,
                'nama' => 'farah atiqa',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'farahatiqa@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 14,
                'lowongan_id' => 2,
                'nama' => 'andi dwi cahyono',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'andidwicahyono@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 15,
                'lowongan_id' => 2,
                'nama' => 'annisa kurniyawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'annisakurniyawati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 16,
                'lowongan_id' => 2,
                'nama' => 'argik fitro',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'argikfitro@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 17,
                'lowongan_id' => 2,
                'nama' => 'eka riswati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ekariswati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 18,
                'lowongan_id' => 2,
                'nama' => 'eko prasetyo',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ekoprasetyo@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 19,
                'lowongan_id' => 2,
                'nama' => 'fitriatus sholihah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'fitriatussholihah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 20,
                'lowongan_id' => 2,
                'nama' => 'fitriyah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'fitriyah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 21,
                'lowongan_id' => 2,
                'nama' => 'ismaya trinurani',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ismayatrinurani@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 22,
                'lowongan_id' => 2,
                'nama' => 'lailatul azizah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'lailatulazizah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 23,
                'lowongan_id' => 2,
                'nama' => 'maslukhin khoirudin',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'maslukhinkhoirudin@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 24,
                'lowongan_id' => 2,
                'nama' => 'muhammad ainur',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'muhammadainur@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 25,
                'lowongan_id' => 2,
                'nama' => 'nadhif andika',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'nadhifandika@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 26,
                'lowongan_id' => 2,
                'nama' => 'palupi dwi kanasih',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'palupidwikanasih@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 27,
                'lowongan_id' => 2,
                'nama' => 'rival dani ardiansyah',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'rivaldaniardiansyah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 28,
                'lowongan_id' => 2,
                'nama' => 'gilang rizqi abdullah',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'gilangrizqiabdullah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 29,
                'lowongan_id' => 2,
                'nama' => 'nur hidayah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'nurhidayah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 30,
                'lowongan_id' => 2,
                'nama' => 'intan purnamasari',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'intanpurnamasari@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 31,
                'lowongan_id' => 2,
                'nama' => 'lena aprilia',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'lenaaprilia@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 32,
                'lowongan_id' => 2,
                'nama' => 'mita listiawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'mitalistiawati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 33,
                'lowongan_id' => 2,
                'nama' => 'nofa anggun sakinah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'nofaanggunsakinah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 34,
                'lowongan_id' => 2,
                'nama' => 'putri amanda',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'putriamanda@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 35,
                'lowongan_id' => 2,
                'nama' => 'yulia anisa putri',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'yuliaanisaputri@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 36,
                'lowongan_id' => 2,
                'nama' => 'zunny nur aulia',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'zunnynuraulia@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 37,
                'lowongan_id' => 2,
                'nama' => 'aldi rusnan',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'aldirusnan@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 38,
                'lowongan_id' => 2,
                'nama' => 'astiti kurniawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'astitikurniawati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 39,
                'lowongan_id' => 2,
                'nama' => 'achmad edy muchin',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'achmadedymuchin@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 40,
                'lowongan_id' => 3,
                'nama' => 'emita nur agustin',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'emitanuragustin@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 41,
                'lowongan_id' => 3,
                'nama' => 'fafit muslimin',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'fafitmuslimin@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 42,
                'lowongan_id' => 3,
                'nama' => 'fiana sari',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'fianasari@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 43,
                'lowongan_id' => 3,
                'nama' => 'lusiana dwi natasya',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'lusianadwinatasya@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 44,
                'lowongan_id' => 3,
                'nama' => 'moh nurhidayat',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'mohnurhidayat@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 45,
                'lowongan_id' => 3,
                'nama' => 'muhammad shayrunizam',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'muhammadshayrunizam@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 46,
                'lowongan_id' => 3,
                'nama' => 'muhammad rifqi dwi prasetyo',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'muhammadrifqidwiprasetyo@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 47,
                'lowongan_id' => 3,
                'nama' => 'suherman almajid',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'suhermanalmajid@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ],
            [
                'id' => 48,
                'lowongan_id' => 3,
                'nama' => 'vevy eka aprilia',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'vevyekaaprilia@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/lamaran/seeder/foto.jpg',
                'url_ijazah' => '/lamaran/seeder/ijazah.jpg',
                'url_ktp' => '/lamaran/seeder/ktp.png',
                'url_skck' => '/lamaran/seeder/skck.jpg',
                'url_riwayat' => '/lamaran/seeder/riwayat.jpg'
            ]
        ]);
    }
}
