<?php

namespace Database\Seeders;

use App\Models\Pelamar;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PelamarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Pelamar::insert([
            [
                'id' => 1,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'Afiya nanda',
                'jenis_kelamin' => 'p',
                'no_telepon' => '0859001338',
                'email' => 'afiyananda@gmail.com',
                'alamat' => 'dsn.songo ds.sukosongo kec kembangbahu kab.lamongan',
                'tanggal_lahir' => '2003-02-10',
                'url_foto' => '/seeder/afiya foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/afiya ktp.jpeg',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/afiya daftar riwayat.jpeg'
            ],
            [
                'id' => 2,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'agelia wati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085707118240',
                'email' => 'ageliawati@gmail.com',
                'alamat' => 'kedungglonggong,sidomukti kembangbahu',
                'tanggal_lahir' => '2003-07-23',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/agelia wati ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/agelia daftar.jpg'
            ],
            [
                'id' => 3,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'agung zainuri',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'agungzainuri@gmail.com',
                'alamat' => 'talun sidogembul sukodadi',
                'tanggal_lahir' => '1999-01-17',
                'url_foto' => '/seeder/agung zainuri fto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/AGUNG ZAINURI kTP.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 4,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'ahmad akhqiq',
                'jenis_kelamin' => 'l',
                'no_telepon' => '081230471090',
                'email' => 'ahmadakhqiq@gmail.com',
                'alamat' => 'gersik',
                'tanggal_lahir' => '2000-05-14',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/ktp.png',
                'url_skck' => '/seeder/akhiq skck.jpeg',
                'url_riwayat' => '/seeder/akhqiq daftar.jpeg'
            ],
            [
                'id' => 5,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'alfarizi',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'alfarizi@gmail.com',
                'alamat' => 'siser rt 002 rw 001 kec.laren',
                'tanggal_lahir' => '2004-04-08',
                'url_foto' => '/seeder/alfarizi foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/alfarizi ktp.jpeg',
                'url_skck' => '/seeder/alfarizi skck.jpeg',
                'url_riwayat' => '/seeder/alfarizi daftar riwayat hidup.jpeg'
            ],
            [
                'id' => 6,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'ana fatmawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '081303200199',
                'email' => 'anafatmawati@gmail.com',
                'alamat' => 'Lembahbang rt 002 rw 001 soko tikung',
                'tanggal_lahir' => '2000-04-30',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/ana ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 7,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'aprilia indah nur jannah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '081450250123',
                'email' => 'apriliaindahnurjannah@gmail.com',
                'alamat' => 'tawun balongtawun sukodadi',
                'tanggal_lahir' => '2002-04-04',
                'url_foto' => '/seeder/aprilia foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/aprilia ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/aprilia riwayat.jpeg'
            ],
            [
                'id' => 8,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'syabilatur rahma',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085739121423',
                'email' => 'syabilaturrahma@gmail.com',
                'alamat' => 'dsn song ds sukosongo kec sukodadi kab lamongan',
                'tanggal_lahir' => '2003-10-22',
                'url_foto' => '/seeder/bela foto.jpeg',
                'url_ijazah' => '/seeder/bela ijazah.jpeg',
                'url_ktp' => '/seeder/bela ktp.jpeg',
                'url_skck' => '/seeder/bela skck.jpeg',
                'url_riwayat' => '/seeder/bela riwayat hidup.jpeg'
            ],
            [
                'id' => 9,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'cicik syahada',
                'jenis_kelamin' => 'p',
                'no_telepon' => '082268794879',
                'email' => 'ciciksyahada@gmail.com',
                'alamat' => 'kedungbanjar sugio',
                'tanggal_lahir' => '2001-03-19',
                'url_foto' => '/seeder/cicik foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpeg',
                'url_ktp' => '/seeder/cicik ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/cicik riwayat.jpeg'
            ],
            [
                'id' => 10,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'denny setiawan',
                'jenis_kelamin' => 'l',
                'no_telepon' => '081396783034',
                'email' => 'dennysetiawan@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/denny ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/denny riwayat.jpeg'
            ],
            [
                'id' => 11,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'eka febrianti',
                'jenis_kelamin' => 'p',
                'no_telepon' => '081515360398',
                'email' => 'ekafebrianti@gmail.com',
                'alamat' => 'banguran sugirejo sukodadi',
                'tanggal_lahir' => '2004-02-09',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/eka ijazah.jpg',
                'url_ktp' => '/seeder/ktp.png',
                'url_skck' => '/seeder/eka skck.jpg',
                'url_riwayat' => '/seeder/eka riwayat.jpg'
            ],
            [
                'id' => 12,
                'user_id' => 2,
                'lowongan_id' => 1,
                'nama' => 'evi kumalasari',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085730119100',
                'email' => 'evikumalasari@gmail.com',
                'alamat' => 'dsn kuati sukosongo kembangbahu',
                'tanggal_lahir' => '2003-03-15',
                'url_foto' => '/seeder/evi foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/evi ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/evi riwayat.jpeg'
            ],
            [
                'id' => 13,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'farah atiqa',
                'jenis_kelamin' => 'p',
                'no_telepon' => '083485071132',
                'email' => 'farahatiqa@gmail.com',
                'alamat' => 'kuati kembangbahu lamongan',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/farah foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/farah ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/farah riwayat.jpeg'
            ],
            [
                'id' => 14,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'andi dwi cahyono',
                'jenis_kelamin' => 'l',
                'no_telepon' => '085670809112',
                'email' => 'andidwicahyono@gmail.com',
                'alamat' => 'siwlan siwalanrejo sukodadi',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/andi dwi foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/andi dwi ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 15,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'annisa kurniyawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085482297491',
                'email' => 'annisakurniyawati@gmail.com',
                'alamat' => 'kudon madulegi sukodadi',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/annisa foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/annisa ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/annisa riwayat.jpeg'
            ],
            [
                'id' => 16,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'argik fitro',
                'jenis_kelamin' => 'l',
                'no_telepon' => '087784644411',
                'email' => 'argikfitro@gmail.com',
                'alamat' => 'menongo sukodadi',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/argik foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/argik ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/argik riwayat.jpeg'
            ],
            [
                'id' => 17,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'eka riswati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '081230412220',
                'email' => 'ekariswati@gmail.com',
                'alamat' => 'kedungbanjar sugio',
                'tanggal_lahir' => '2002-07-23',
                'url_foto' => '/seeder/eka riswati foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/eka riswati ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/eka riswati riwayat.jpeg'
            ],
            [
                'id' => 18,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'eko prasetyo',
                'jenis_kelamin' => 'p',
                'no_telepon' => '0857084890132',
                'email' => 'ekoprasetyo@gmail.com',
                'alamat' => 'dorogede gedangan sukodadi',
                'tanggal_lahir' => '2001-10-02',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/eko ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/eko riwayat.jpeg'
            ],
            [
                'id' => 19,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'fitriatus sholihah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085846464646',
                'email' => 'fitriatussholihah@gmail.com',
                'alamat' => 'bagel sumberagung sukodadi',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/fitriatus foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/fitriatus ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/fitriatus riwayat.jpeg'
            ],
            [
                'id' => 20,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'fitriyah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '081202303461',
                'email' => 'fitriyah@gmail.com',
                'alamat' => 'gempol gedangan sukodadi',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/fitriyah foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/fitriyah ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/fitriyah riwayat.jpeg'
            ],
            [
                'id' => 21,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'ismaya trinurani',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08174751884',
                'email' => 'ismayatrinurani@gmail.com',
                'alamat' => 'semlawang surabayan sukodadi',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/ismaya foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/ismaya riwayat.jpeg'
            ],
            [
                'id' => 22,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'lailatul azizah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '0853489010025',
                'email' => 'lailatulazizah@gmail.com',
                'alamat' => 'bulu bandungsari sukodadi',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/lailatul foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/lailatul ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/lailatul riwayat.jpeg'
            ],
            [
                'id' => 23,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'maslukhin khoirudin',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'maslukhinkhoirudin@gmail.com',
                'alamat' => 'jirekan rt 01 rw 02 balungtawun',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/maslukin ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 24,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'muhammad ainur',
                'jenis_kelamin' => 'l',
                'no_telepon' => '081878554139',
                'email' => 'muhammadainur@gmail.com',
                'alamat' => 'bandungsari sukodadi',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/ainur ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/ainur riwayat.jpeg'
            ],
            [
                'id' => 25,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'nadhif andika',
                'jenis_kelamin' => 'l',
                'no_telepon' => '085450201002',
                'email' => 'nadhifandika@gmail.com',
                'alamat' => 'ngiprik rt 004 rw 004 madulegi',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/nadhif foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/nadhif ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 26,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'palupi dwi kanasih',
                'jenis_kelamin' => 'p',
                'no_telepon' => '081345779847',
                'email' => 'palupidwikanasih@gmail.com',
                'alamat' => 'sumlaran surabayan',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/palupi foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/palupi ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/palupi riwayat.jpeg'
            ],
            [
                'id' => 27,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'rival dani ardiansyah',
                'jenis_kelamin' => 'l',
                'no_telepon' => '085123490112',
                'email' => 'rivaldaniardiansyah@gmail.com',
                'alamat' => 'pagak sidogembul sukodadi',
                'tanggal_lahir' => '2002-04-17',
                'url_foto' => '/seeder/rival foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/rival ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 28,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'gilang rizqi abdullah',
                'jenis_kelamin' => 'l',
                'no_telepon' => '085678909800',
                'email' => 'gilangrizqiabdullah@gmail.com',
                'alamat' => 'pekaja kalibogor jawa tengah',
                'tanggal_lahir' => '1998-02-16',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/GILANG KTP.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 29,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'nur hidayah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085604460996',
                'email' => 'nurhidayah@gmail.com',
                'alamat' => 'dsn suci ds jubellor sugio',
                'tanggal_lahir' => '2003-05-06',
                'url_foto' => '/seeder/hidaya foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/hidaya ktp.png',
                'url_skck' => '/seeder/hidaya skck.jpg',
                'url_riwayat' => '/seeder/hidaya riwayat.jpeg'
            ],
            [
                'id' => 30,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'intan purnamasari',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085404200404',
                'email' => 'intanpurnamasari@gmail.com',
                'alamat' => 'cabean baturono',
                'tanggal_lahir' => '2002-01-22',
                'url_foto' => '/seeder/intan foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/intan ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 31,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'lena aprilia',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085908776212',
                'email' => 'lenaaprilia@gmail.com',
                'alamat' => 'sukoanyar sidomukti kembangbahu',
                'tanggal_lahir' => '2003-03-15',
                'url_foto' => '/seeder/lena foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/lena ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 32,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'mita listiawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '01222309804',
                'email' => 'mitalistiawati@gmail.com',
                'alamat' => 'randeka,soko tikung',
                'tanggal_lahir' => '2002-01-22',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/mita ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 33,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'nofa anggun sakinah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'nofaanggunsakinah@gmail.com',
                'alamat' => 'pagak sidogembul sukodadi',
                'tanggal_lahir' => '2003-04-15',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/nofa ijazah.jpeg',
                'url_ktp' => '/seeder/nofa ktp.png',
                'url_skck' => '/seeder/nofa skck.jpeg',
                'url_riwayat' => '/seeder/nofa riwayat.jpeg'
            ],
            [
                'id' => 34,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'putri amanda',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085435678909',
                'email' => 'putriamanda@gmail.com',
                'alamat' => 'menongo sukodadi',
                'tanggal_lahir' => '2004-11-20',
                'url_foto' => '/seeder/putri foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/putri ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 35,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'yulia anisa putri',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085713505128',
                'email' => 'yuliaanisaputri@gmail.com',
                'alamat' => 'dsn pinggiran ds sumberagung kec sukodadi',
                'tanggal_lahir' => '2003-07-01',
                'url_foto' => '/seeder/foto.jpeg',
                'url_ijazah' => '/seeder/yulia ijazah.jpeg',
                'url_ktp' => '/seeder/yulia ktp.png',
                'url_skck' => '/seeder/yulia skck.jpeg',
                'url_riwayat' => '/seeder/yulia riwayat.jpeg'
            ],
            [
                'id' => 36,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'zunny nur aulia',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085678980112',
                'email' => 'zunnynuraulia@gmail.com',
                'alamat' => 'songo sukosongo kembangbahu',
                'tanggal_lahir' => '2003-04-04',
                'url_foto' => '/seeder/zunny foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/zunny ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 37,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'aldi rusnan',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'aldirusnan@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 38,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'astiti kurniawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085706309327',
                'email' => 'astitikurniawati@gmail.com',
                'alamat' => 'dsn bali ds pelumpang',
                'tanggal_lahir' => '1996-04-03',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/asti ijazah.jpeg',
                'url_ktp' => '/seeder/ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/asti riwayat.jpeg'
            ],
            [
                'id' => 39,
                'user_id' => 2,
                'lowongan_id' => 2,
                'nama' => 'achmad edy muchin',
                'jenis_kelamin' => 'l',
                'no_telepon' => '085706309327',
                'email' => 'achmadedymuchin@gmail.com',
                'alamat' => 'dsn bali ds pelumpang',
                'tanggal_lahir' => '1994-12-27',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/edy ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/edy riwayat.jpeg'
            ],
            [
                'id' => 40,
                'user_id' => 2,
                'lowongan_id' => 3,
                'nama' => 'emita nur agustin',
                'jenis_kelamin' => 'p',
                'no_telepon' => '083138510581',
                'email' => 'emitanuragustin@gmail.com',
                'alamat' => 'songo sukosongo kembangbahu',
                'tanggal_lahir' => '2003-03-20',
                'url_foto' => '/seeder/emita foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpeg',
                'url_ktp' => '/seeder/emita ktp.png',
                'url_skck' => '/seeder/emita skck.jpeg',
                'url_riwayat' => '/seeder/emita riwayat.jpeg'
            ],
            [
                'id' => 41,
                'user_id' => 2,
                'lowongan_id' => 3,
                'nama' => 'fafit muslimin',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'fafitmuslimin@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 42,
                'user_id' => 2,
                'lowongan_id' => 3,
                'nama' => 'fiana sari',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08123046034',
                'email' => 'fianasari@gmail.com',
                'alamat' => 'menongo rt 02 rw 03',
                'tanggal_lahir' => '2003-03-01',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ fiana ijazah.jpeg',
                'url_ktp' => '/seeder/ktp.png',
                'url_skck' => '/seeder/fiana skck.jpeg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 43,
                'user_id' => 2,
                'lowongan_id' => 3,
                'nama' => 'lusiana dwi natasya',
                'jenis_kelamin' => 'p',
                'no_telepon' => '081559550549',
                'email' => 'lusianadwinatasya@gmail.com',
                'alamat' => 'babatkumpul pucuk lamongan',
                'tanggal_lahir' => '2005-01-05',
                'url_foto' => '/seeder/lusiana foto.jpeg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/lusiana ktp.png',
                'url_skck' => '/seeder/lusiana skck.jpeg',
                'url_riwayat' => '/seeder/lusiana riwayat.jpeg'
            ],
            [
                'id' => 44,
                'user_id' => 2,
                'lowongan_id' => 3,
                'nama' => 'moh nurhidayat',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'mohnurhidayat@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 45,
                'user_id' => 2,
                'lowongan_id' => 3,
                'nama' => 'muhammad shayrunizam',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'muhammadshayrunizam@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 46,
                'user_id' => 2,
                'lowongan_id' => 3,
                'nama' => 'muhammad rifqi dwi prasetyo',
                'jenis_kelamin' => 'l',
                'no_telepon' => '081234566120',
                'email' => 'muhammadrifqidwiprasetyo@gmail.com',
                'alamat' => 'dsn dalit ds tukkerto deket',
                'tanggal_lahir' => '2003-07-14',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/rifqi ijazah.jpeg',
                'url_ktp' => '/seeder/rifqi ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 47,
                'user_id' => 2,
                'lowongan_id' => 3,
                'nama' => 'suherman almajid',
                'jenis_kelamin' => 'l',
                'no_telepon' => '08812345678',
                'email' => 'suhermanalmajid@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ],
            [
                'id' => 48,
                'user_id' => 2,
                'lowongan_id' => 3,
                'nama' => 'vevy eka aprilia',
                'jenis_kelamin' => 'p',
                'no_telepon' => '085888909210',
                'email' => 'vevyekaaprilia@gmail.com',
                'alamat' => 'karangtengah rt 001 rw 001sukosongo',
                'tanggal_lahir' => '2004-04-21',
                'url_foto' => '/seeder/foto.jpg',
                'url_ijazah' => '/seeder/ijazah.jpg',
                'url_ktp' => '/seeder/vevi ktp.png',
                'url_skck' => '/seeder/skck.jpg',
                'url_riwayat' => '/seeder/riwayat.jpg'
            ]
        ]);
    }
}
