<?php

namespace Database\Seeders;

use App\Models\Pelamar;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PelamarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Pelamar::insert([
            [
                'id' => 1,
                'lowongan_id' => 2,
                'nama' => 'Afiya nanda',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'afiyananda@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_1.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_1.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_1.jpg',
                'url_skck' => 'https://example.com/uploads/skck_1.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_1.jpg'
            ],
            [
                'id' => 2,
                'lowongan_id' => 2,
                'nama' => 'agelia wati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ageliawati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_2.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_2.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_2.jpg',
                'url_skck' => 'https://example.com/uploads/skck_2.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_2.jpg'
            ],
            [
                'id' => 3,
                'lowongan_id' => 2,
                'nama' => 'agung zainuri',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'agungzainuri@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_3.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_3.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_3.jpg',
                'url_skck' => 'https://example.com/uploads/skck_3.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_3.jpg'
            ],
            [
                'id' => 4,
                'lowongan_id' => 2,
                'nama' => 'ahmad akhqiq',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ahmadakhqiq@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_4.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_4.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_4.jpg',
                'url_skck' => 'https://example.com/uploads/skck_4.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_4.jpg'
            ],
            [
                'id' => 5,
                'lowongan_id' => 2,
                'nama' => 'alfarizi',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'alfarizi@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_5.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_5.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_5.jpg',
                'url_skck' => 'https://example.com/uploads/skck_5.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_5.jpg'
            ],
            [
                'id' => 6,
                'lowongan_id' => 2,
                'nama' => 'ana fatmawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'anafatmawati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_6.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_6.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_6.jpg',
                'url_skck' => 'https://example.com/uploads/skck_6.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_6.jpg'
            ],
            [
                'id' => 7,
                'lowongan_id' => 2,
                'nama' => 'aprilia indah nur jannah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'apriliaindahnurjannah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_7.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_7.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_7.jpg',
                'url_skck' => 'https://example.com/uploads/skck_7.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_7.jpg'
            ],
            [
                'id' => 8,
                'lowongan_id' => 2,
                'nama' => 'syabilatur rahma',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'syabilaturrahma@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_8.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_8.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_8.jpg',
                'url_skck' => 'https://example.com/uploads/skck_8.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_8.jpg'
            ],
            [
                'id' => 9,
                'lowongan_id' => 2,
                'nama' => 'cicik syahada',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ciciksyahada@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_9.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_9.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_9.jpg',
                'url_skck' => 'https://example.com/uploads/skck_9.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_9.jpg'
            ],
            [
                'id' => 10,
                'lowongan_id' => 2,
                'nama' => 'denny setiawan',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'dennysetiawan@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_10.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_10.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_10.jpg',
                'url_skck' => 'https://example.com/uploads/skck_10.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_10.jpg'
            ],
            [
                'id' => 11,
                'lowongan_id' => 2,
                'nama' => 'eka febrianti',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ekafebrianti@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_11.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_11.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_11.jpg',
                'url_skck' => 'https://example.com/uploads/skck_11.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_11.jpg'
            ],
            [
                'id' => 12,
                'lowongan_id' => 2,
                'nama' => 'evi kumalasari',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'evikumalasari@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_12.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_12.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_12.jpg',
                'url_skck' => 'https://example.com/uploads/skck_12.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_12.jpg'
            ],
            [
                'id' => 13,
                'lowongan_id' => 2,
                'nama' => 'farah atiqa',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'farahatiqa@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_13.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_13.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_13.jpg',
                'url_skck' => 'https://example.com/uploads/skck_13.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_13.jpg'
            ],
            [
                'id' => 14,
                'lowongan_id' => 2,
                'nama' => 'andi dwi cahyono',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'andidwicahyono@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_14.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_14.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_14.jpg',
                'url_skck' => 'https://example.com/uploads/skck_14.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_14.jpg'
            ],
            [
                'id' => 15,
                'lowongan_id' => 2,
                'nama' => 'annisa kurniyawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'annisakurniyawati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_15.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_15.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_15.jpg',
                'url_skck' => 'https://example.com/uploads/skck_15.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_15.jpg'
            ],
            [
                'id' => 16,
                'lowongan_id' => 2,
                'nama' => 'argik fitro',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'argikfitro@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_16.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_16.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_16.jpg',
                'url_skck' => 'https://example.com/uploads/skck_16.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_16.jpg'
            ],
            [
                'id' => 17,
                'lowongan_id' => 2,
                'nama' => 'eka riswati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ekariswati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_17.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_17.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_17.jpg',
                'url_skck' => 'https://example.com/uploads/skck_17.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_17.jpg'
            ],
            [
                'id' => 18,
                'lowongan_id' => 2,
                'nama' => 'eko prasetyo',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ekoprasetyo@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_18.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_18.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_18.jpg',
                'url_skck' => 'https://example.com/uploads/skck_18.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_18.jpg'
            ],
            [
                'id' => 19,
                'lowongan_id' => 2,
                'nama' => 'fitriatus sholihah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'fitriatussholihah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_19.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_19.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_19.jpg',
                'url_skck' => 'https://example.com/uploads/skck_19.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_19.jpg'
            ],
            [
                'id' => 20,
                'lowongan_id' => 2,
                'nama' => 'fitriyah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'fitriyah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_20.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_20.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_20.jpg',
                'url_skck' => 'https://example.com/uploads/skck_20.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_20.jpg'
            ],
            [
                'id' => 21,
                'lowongan_id' => 2,
                'nama' => 'ismaya trinurani',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'ismayatrinurani@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_21.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_21.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_21.jpg',
                'url_skck' => 'https://example.com/uploads/skck_21.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_21.jpg'
            ],
            [
                'id' => 22,
                'lowongan_id' => 2,
                'nama' => 'lailatul azizah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'lailatulazizah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_22.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_22.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_22.jpg',
                'url_skck' => 'https://example.com/uploads/skck_22.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_22.jpg'
            ],
            [
                'id' => 23,
                'lowongan_id' => 2,
                'nama' => 'maslukhin khoirudin',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'maslukhinkhoirudin@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_23.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_23.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_23.jpg',
                'url_skck' => 'https://example.com/uploads/skck_23.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_23.jpg'
            ],
            [
                'id' => 24,
                'lowongan_id' => 2,
                'nama' => 'muhammad ainur',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'muhammadainur@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_24.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_24.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_24.jpg',
                'url_skck' => 'https://example.com/uploads/skck_24.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_24.jpg'
            ],
            [
                'id' => 25,
                'lowongan_id' => 2,
                'nama' => 'nadhif andika',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'nadhifandika@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_25.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_25.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_25.jpg',
                'url_skck' => 'https://example.com/uploads/skck_25.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_25.jpg'
            ],
            [
                'id' => 26,
                'lowongan_id' => 2,
                'nama' => 'palupi dwi kanasih',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'palupidwikanasih@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_26.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_26.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_26.jpg',
                'url_skck' => 'https://example.com/uploads/skck_26.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_26.jpg'
            ],
            [
                'id' => 27,
                'lowongan_id' => 2,
                'nama' => 'rival dani ardiansyah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'rivaldaniardiansyah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_27.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_27.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_27.jpg',
                'url_skck' => 'https://example.com/uploads/skck_27.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_27.jpg'
            ],
            [
                'id' => 28,
                'lowongan_id' => 2,
                'nama' => 'gilang rizqi abdullah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'gilangrizqiabdullah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_28.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_28.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_28.jpg',
                'url_skck' => 'https://example.com/uploads/skck_28.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_28.jpg'
            ],
            [
                'id' => 29,
                'lowongan_id' => 2,
                'nama' => 'nur hidayah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'nurhidayah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_29.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_29.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_29.jpg',
                'url_skck' => 'https://example.com/uploads/skck_29.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_29.jpg'
            ],
            [
                'id' => 30,
                'lowongan_id' => 2,
                'nama' => 'intan purnamasari',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'intanpurnamasari@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_30.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_30.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_30.jpg',
                'url_skck' => 'https://example.com/uploads/skck_30.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_30.jpg'
            ],
            [
                'id' => 31,
                'lowongan_id' => 2,
                'nama' => 'lena aprilia',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'lenaaprilia@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_31.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_31.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_31.jpg',
                'url_skck' => 'https://example.com/uploads/skck_31.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_31.jpg'
            ],
            [
                'id' => 32,
                'lowongan_id' => 2,
                'nama' => 'mita listiawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'mitalistiawati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_32.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_32.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_32.jpg',
                'url_skck' => 'https://example.com/uploads/skck_32.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_32.jpg'
            ],
            [
                'id' => 33,
                'lowongan_id' => 2,
                'nama' => 'nofa anggun sakinah',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'nofaanggunsakinah@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_33.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_33.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_33.jpg',
                'url_skck' => 'https://example.com/uploads/skck_33.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_33.jpg'
            ],
            [
                'id' => 34,
                'lowongan_id' => 2,
                'nama' => 'putri amanda',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'putriamanda@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_34.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_34.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_34.jpg',
                'url_skck' => 'https://example.com/uploads/skck_34.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_34.jpg'
            ],
            [
                'id' => 35,
                'lowongan_id' => 2,
                'nama' => 'yulia anisa putri',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'yuliaanisaputri@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_35.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_35.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_35.jpg',
                'url_skck' => 'https://example.com/uploads/skck_35.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_35.jpg'
            ],
            [
                'id' => 36,
                'lowongan_id' => 2,
                'nama' => 'zunny nur aulia',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'zunnynuraulia@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_36.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_36.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_36.jpg',
                'url_skck' => 'https://example.com/uploads/skck_36.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_36.jpg'
            ],
            [
                'id' => 37,
                'lowongan_id' => 2,
                'nama' => 'aldi rusnan',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'aldirusnan@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_37.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_37.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_37.jpg',
                'url_skck' => 'https://example.com/uploads/skck_37.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_37.jpg'
            ],
            [
                'id' => 38,
                'lowongan_id' => 2,
                'nama' => 'astiti kurniawati',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'astitikurniawati@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_38.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_38.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_38.jpg',
                'url_skck' => 'https://example.com/uploads/skck_38.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_38.jpg'
            ],
            [
                'id' => 39,
                'lowongan_id' => 2,
                'nama' => 'achmad edy muchin',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'achmadedymuchin@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_39.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_39.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_39.jpg',
                'url_skck' => 'https://example.com/uploads/skck_39.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_39.jpg'
            ],
            [
                'id' => 40,
                'lowongan_id' => 2,
                'nama' => 'emita nur agustin',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'emitanuragustin@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_40.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_40.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_40.jpg',
                'url_skck' => 'https://example.com/uploads/skck_40.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_40.jpg'
            ],
            [
                'id' => 41,
                'lowongan_id' => 2,
                'nama' => 'fafit muslimin',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'fafitmuslimin@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_41.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_41.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_41.jpg',
                'url_skck' => 'https://example.com/uploads/skck_41.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_41.jpg'
            ],
            [
                'id' => 42,
                'lowongan_id' => 2,
                'nama' => 'fiana sari',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'fianasari@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_42.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_42.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_42.jpg',
                'url_skck' => 'https://example.com/uploads/skck_42.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_42.jpg'
            ],
            [
                'id' => 43,
                'lowongan_id' => 2,
                'nama' => 'lusiana dwi natasya',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'lusianadwinatasya@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_43.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_43.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_43.jpg',
                'url_skck' => 'https://example.com/uploads/skck_43.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_43.jpg'
            ],
            [
                'id' => 44,
                'lowongan_id' => 2,
                'nama' => 'moh nurhidayat',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'mohnurhidayat@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_44.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_44.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_44.jpg',
                'url_skck' => 'https://example.com/uploads/skck_44.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_44.jpg'
            ],
            [
                'id' => 45,
                'lowongan_id' => 2,
                'nama' => 'muhammad shayrunizam',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'muhammadshayrunizam@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_45.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_45.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_45.jpg',
                'url_skck' => 'https://example.com/uploads/skck_45.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_45.jpg'
            ],
            [
                'id' => 46,
                'lowongan_id' => 2,
                'nama' => 'muhammad rifqi dwi prasetyo',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'muhammadrifqidwiprasetyo@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_46.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_46.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_46.jpg',
                'url_skck' => 'https://example.com/uploads/skck_46.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_46.jpg'
            ],
            [
                'id' => 47,
                'lowongan_id' => 2,
                'nama' => 'suherman almajid',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'suhermanalmajid@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_47.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_47.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_47.jpg',
                'url_skck' => 'https://example.com/uploads/skck_47.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_47.jpg'
            ],
            [
                'id' => 48,
                'lowongan_id' => 2,
                'nama' => 'vevy eka aprilia',
                'jenis_kelamin' => 'p',
                'no_telepon' => '08812345678',
                'email' => 'vevyekaaprilia@gmail.com',
                'alamat' => 'Alamat contoh',
                'tanggal_lahir' => '2000-01-01',
                'url_foto' => 'https://example.com/uploads/foto_48.jpg',
                'url_ijazah' => 'https://example.com/uploads/ijazah_48.jpg',
                'url_ktp' => 'https://example.com/uploads/ktp_48.jpg',
                'url_skck' => 'https://example.com/uploads/skck_48.jpg',
                'url_riwayat' => 'https://example.com/uploads/riwayat_48.jpg'
            ]
        ]);
    }
}
